################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../tensorflow-lite/tensorflow/lite/micro/kernels/activations.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/activations_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/add_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/add_n.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/arg_min_max.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/assign_variable.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/batch_matmul.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_args.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_to.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/call_once.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/cast.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/ceil.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/comparisons.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/concatenation.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/conv_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/cumsum.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/depth_to_space.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/dequantize.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/dequantize_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/div.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/elementwise.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/elu.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/embedding_lookup.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/ethosu.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/exp.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/expand_dims.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/fill.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/floor.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/floor_div.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/floor_mod.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/gather.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/gather_nd.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/if.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/kernel_runner.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/kernel_util.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/l2norm.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/log_softmax.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/logical.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/logical_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/logistic.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/logistic_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/mirror_pad.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/mul_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/neg.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/pack.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/pad.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/pooling_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/prelu.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/prelu_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/quantize.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/quantize_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/read_variable.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/reduce.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/reduce_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/reshape.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/reshape_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/round.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/select.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/shape.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/slice.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/softmax_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/space_to_depth.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/split.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/split_v.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/squared_difference.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/squeeze.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/sub.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/sub_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/svdf_common.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/tanh.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/transpose.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/unpack.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/var_handle.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/while.cc \
../tensorflow-lite/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./tensorflow-lite/tensorflow/lite/micro/kernels/activations.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/activations_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/add_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/add_n.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/arg_min_max.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/assign_variable.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/batch_matmul.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_args.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_to.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/call_once.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/cast.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/ceil.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/comparisons.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/concatenation.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/conv_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/cumsum.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/depth_to_space.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/detection_postprocess.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/div.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/elementwise.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/elu.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/embedding_lookup.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/ethosu.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/exp.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/expand_dims.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/fill.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/floor.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/floor_div.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/floor_mod.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/fully_connected_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/gather.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/gather_nd.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/if.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_runner.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_util.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/l2norm.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/log_softmax.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/logical.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/logical_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/logistic.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/logistic_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/maximum_minimum.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/mirror_pad.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/mul_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/neg.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/pack.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/pad.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/pooling_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/prelu.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/prelu_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/quantize.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/quantize_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/read_variable.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/reduce.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/reduce_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/reshape.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/reshape_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/resize_bilinear.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/round.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/select.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/shape.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/slice.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/softmax_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_depth.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/split.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/split_v.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/squared_difference.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/squeeze.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/sub.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/sub_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/svdf_common.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/tanh.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/transpose.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/unpack.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/var_handle.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/while.d \
./tensorflow-lite/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./tensorflow-lite/tensorflow/lite/micro/kernels/activations.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/activations_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/add_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/add_n.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/arg_min_max.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/assign_variable.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/batch_matmul.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_args.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_to.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/call_once.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/cast.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/ceil.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/comparisons.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/concatenation.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/conv_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/cumsum.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/depth_to_space.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/detection_postprocess.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/div.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/elementwise.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/elu.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/embedding_lookup.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/ethosu.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/exp.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/expand_dims.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/fill.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/floor.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/floor_div.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/floor_mod.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/fully_connected_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/gather.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/gather_nd.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/if.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_runner.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_util.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/l2norm.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/log_softmax.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/logical.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/logical_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/logistic.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/logistic_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/maximum_minimum.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/mirror_pad.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/mul_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/neg.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/pack.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/pad.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/pooling_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/prelu.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/prelu_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/quantize.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/quantize_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/read_variable.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/reduce.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/reduce_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/reshape.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/reshape_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/resize_bilinear.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/round.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/select.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/shape.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/slice.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/softmax_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_depth.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/split.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/split_v.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/squared_difference.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/squeeze.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/sub.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/sub_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/svdf_common.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/tanh.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/transpose.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/unpack.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/var_handle.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/while.o \
./tensorflow-lite/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
tensorflow-lite/tensorflow/lite/micro/kernels/%.o tensorflow-lite/tensorflow/lite/micro/kernels/%.su tensorflow-lite/tensorflow/lite/micro/kernels/%.cyclo: ../tensorflow-lite/tensorflow/lite/micro/kernels/%.cc tensorflow-lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DSTM32F429xx -DCMSIS_NN -DSTM32F429I_DISC1 -DSTM32 -DSTM32F429ZITx -DSTM32F4 -c -I../Inc -I"/home/rmknan/STM32CubeIDE/workspace_1.15.0/Alphabet_Recognition/tensorflow-lite/third_party/kissfft" -I"/home/rmknan/STM32CubeIDE/workspace_1.15.0/Alphabet_Recognition/tensorflow-lite/third_party/cmsis_nn/Include" -I"/home/rmknan/STM32CubeIDE/workspace_1.15.0/Alphabet_Recognition/tensorflow-lite/third_party/cmsis_nn" -I"/home/rmknan/STM32CubeIDE/workspace_1.15.0/Alphabet_Recognition/tensorflow-lite" -I"/home/rmknan/STM32CubeIDE/workspace_1.15.0/Alphabet_Recognition/tensorflow-lite/third_party/ruy" -I"/home/rmknan/STM32CubeIDE/workspace_1.15.0/Alphabet_Recognition/tensorflow-lite/third_party/gemmlowp" -I"/home/rmknan/STM32CubeIDE/workspace_1.15.0/Alphabet_Recognition/tensorflow-lite/third_party/flatbuffers/include" -I"/home/rmknan/STM32CubeIDE/workspace_1.15.0/Alphabet_Recognition/libs/stm32" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-tensorflow-2d-lite-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-tensorflow-2d-lite-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./tensorflow-lite/tensorflow/lite/micro/kernels/activations.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/activations.d ./tensorflow-lite/tensorflow/lite/micro/kernels/activations.o ./tensorflow-lite/tensorflow/lite/micro/kernels/activations.su ./tensorflow-lite/tensorflow/lite/micro/kernels/activations_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/activations_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/activations_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/activations_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/add_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/add_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/add_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/add_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/add_n.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/add_n.d ./tensorflow-lite/tensorflow/lite/micro/kernels/add_n.o ./tensorflow-lite/tensorflow/lite/micro/kernels/add_n.su ./tensorflow-lite/tensorflow/lite/micro/kernels/arg_min_max.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/arg_min_max.d ./tensorflow-lite/tensorflow/lite/micro/kernels/arg_min_max.o ./tensorflow-lite/tensorflow/lite/micro/kernels/arg_min_max.su ./tensorflow-lite/tensorflow/lite/micro/kernels/assign_variable.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/assign_variable.d ./tensorflow-lite/tensorflow/lite/micro/kernels/assign_variable.o ./tensorflow-lite/tensorflow/lite/micro/kernels/assign_variable.su ./tensorflow-lite/tensorflow/lite/micro/kernels/batch_matmul.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/batch_matmul.d ./tensorflow-lite/tensorflow/lite/micro/kernels/batch_matmul.o ./tensorflow-lite/tensorflow/lite/micro/kernels/batch_matmul.su ./tensorflow-lite/tensorflow/lite/micro/kernels/batch_to_space_nd.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./tensorflow-lite/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./tensorflow-lite/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_args.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_args.d ./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_args.o ./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_args.su ./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_to.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_to.d ./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_to.o ./tensorflow-lite/tensorflow/lite/micro/kernels/broadcast_to.su ./tensorflow-lite/tensorflow/lite/micro/kernels/call_once.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/call_once.d ./tensorflow-lite/tensorflow/lite/micro/kernels/call_once.o ./tensorflow-lite/tensorflow/lite/micro/kernels/call_once.su ./tensorflow-lite/tensorflow/lite/micro/kernels/cast.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/cast.d ./tensorflow-lite/tensorflow/lite/micro/kernels/cast.o ./tensorflow-lite/tensorflow/lite/micro/kernels/cast.su ./tensorflow-lite/tensorflow/lite/micro/kernels/ceil.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/ceil.d ./tensorflow-lite/tensorflow/lite/micro/kernels/ceil.o ./tensorflow-lite/tensorflow/lite/micro/kernels/ceil.su ./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer.d ./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer.o ./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer.su ./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/circular_buffer_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/comparisons.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/comparisons.d ./tensorflow-lite/tensorflow/lite/micro/kernels/comparisons.o ./tensorflow-lite/tensorflow/lite/micro/kernels/comparisons.su ./tensorflow-lite/tensorflow/lite/micro/kernels/concatenation.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/concatenation.d ./tensorflow-lite/tensorflow/lite/micro/kernels/concatenation.o ./tensorflow-lite/tensorflow/lite/micro/kernels/concatenation.su ./tensorflow-lite/tensorflow/lite/micro/kernels/conv_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/conv_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/conv_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/conv_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/cumsum.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/cumsum.d ./tensorflow-lite/tensorflow/lite/micro/kernels/cumsum.o ./tensorflow-lite/tensorflow/lite/micro/kernels/cumsum.su ./tensorflow-lite/tensorflow/lite/micro/kernels/depth_to_space.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/depth_to_space.d ./tensorflow-lite/tensorflow/lite/micro/kernels/depth_to_space.o ./tensorflow-lite/tensorflow/lite/micro/kernels/depth_to_space.su ./tensorflow-lite/tensorflow/lite/micro/kernels/depthwise_conv_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize.d ./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize.o ./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize.su ./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/dequantize_common.su
	-$(RM) ./tensorflow-lite/tensorflow/lite/micro/kernels/detection_postprocess.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/detection_postprocess.d ./tensorflow-lite/tensorflow/lite/micro/kernels/detection_postprocess.o ./tensorflow-lite/tensorflow/lite/micro/kernels/detection_postprocess.su ./tensorflow-lite/tensorflow/lite/micro/kernels/div.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/div.d ./tensorflow-lite/tensorflow/lite/micro/kernels/div.o ./tensorflow-lite/tensorflow/lite/micro/kernels/div.su ./tensorflow-lite/tensorflow/lite/micro/kernels/elementwise.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/elementwise.d ./tensorflow-lite/tensorflow/lite/micro/kernels/elementwise.o ./tensorflow-lite/tensorflow/lite/micro/kernels/elementwise.su ./tensorflow-lite/tensorflow/lite/micro/kernels/elu.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/elu.d ./tensorflow-lite/tensorflow/lite/micro/kernels/elu.o ./tensorflow-lite/tensorflow/lite/micro/kernels/elu.su ./tensorflow-lite/tensorflow/lite/micro/kernels/embedding_lookup.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/embedding_lookup.d ./tensorflow-lite/tensorflow/lite/micro/kernels/embedding_lookup.o ./tensorflow-lite/tensorflow/lite/micro/kernels/embedding_lookup.su ./tensorflow-lite/tensorflow/lite/micro/kernels/ethosu.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/ethosu.d ./tensorflow-lite/tensorflow/lite/micro/kernels/ethosu.o ./tensorflow-lite/tensorflow/lite/micro/kernels/ethosu.su ./tensorflow-lite/tensorflow/lite/micro/kernels/exp.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/exp.d ./tensorflow-lite/tensorflow/lite/micro/kernels/exp.o ./tensorflow-lite/tensorflow/lite/micro/kernels/exp.su ./tensorflow-lite/tensorflow/lite/micro/kernels/expand_dims.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/expand_dims.d ./tensorflow-lite/tensorflow/lite/micro/kernels/expand_dims.o ./tensorflow-lite/tensorflow/lite/micro/kernels/expand_dims.su ./tensorflow-lite/tensorflow/lite/micro/kernels/fill.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/fill.d ./tensorflow-lite/tensorflow/lite/micro/kernels/fill.o ./tensorflow-lite/tensorflow/lite/micro/kernels/fill.su ./tensorflow-lite/tensorflow/lite/micro/kernels/floor.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/floor.d ./tensorflow-lite/tensorflow/lite/micro/kernels/floor.o ./tensorflow-lite/tensorflow/lite/micro/kernels/floor.su ./tensorflow-lite/tensorflow/lite/micro/kernels/floor_div.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/floor_div.d ./tensorflow-lite/tensorflow/lite/micro/kernels/floor_div.o ./tensorflow-lite/tensorflow/lite/micro/kernels/floor_div.su ./tensorflow-lite/tensorflow/lite/micro/kernels/floor_mod.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/floor_mod.d ./tensorflow-lite/tensorflow/lite/micro/kernels/floor_mod.o ./tensorflow-lite/tensorflow/lite/micro/kernels/floor_mod.su ./tensorflow-lite/tensorflow/lite/micro/kernels/fully_connected_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/fully_connected_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/fully_connected_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/fully_connected_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/gather.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/gather.d ./tensorflow-lite/tensorflow/lite/micro/kernels/gather.o ./tensorflow-lite/tensorflow/lite/micro/kernels/gather.su ./tensorflow-lite/tensorflow/lite/micro/kernels/gather_nd.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/gather_nd.d ./tensorflow-lite/tensorflow/lite/micro/kernels/gather_nd.o ./tensorflow-lite/tensorflow/lite/micro/kernels/gather_nd.su ./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish.d ./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish.o ./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish.su ./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/hard_swish_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/if.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/if.d ./tensorflow-lite/tensorflow/lite/micro/kernels/if.o ./tensorflow-lite/tensorflow/lite/micro/kernels/if.su ./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_runner.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_runner.d ./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_runner.o ./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_runner.su ./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_util.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_util.d ./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_util.o ./tensorflow-lite/tensorflow/lite/micro/kernels/kernel_util.su ./tensorflow-lite/tensorflow/lite/micro/kernels/l2_pool_2d.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/l2_pool_2d.d ./tensorflow-lite/tensorflow/lite/micro/kernels/l2_pool_2d.o ./tensorflow-lite/tensorflow/lite/micro/kernels/l2_pool_2d.su ./tensorflow-lite/tensorflow/lite/micro/kernels/l2norm.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/l2norm.d ./tensorflow-lite/tensorflow/lite/micro/kernels/l2norm.o ./tensorflow-lite/tensorflow/lite/micro/kernels/l2norm.su ./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu.d ./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu.o ./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu.su ./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/leaky_relu_common.su
	-$(RM) ./tensorflow-lite/tensorflow/lite/micro/kernels/log_softmax.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/log_softmax.d ./tensorflow-lite/tensorflow/lite/micro/kernels/log_softmax.o ./tensorflow-lite/tensorflow/lite/micro/kernels/log_softmax.su ./tensorflow-lite/tensorflow/lite/micro/kernels/logical.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/logical.d ./tensorflow-lite/tensorflow/lite/micro/kernels/logical.o ./tensorflow-lite/tensorflow/lite/micro/kernels/logical.su ./tensorflow-lite/tensorflow/lite/micro/kernels/logical_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/logical_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/logical_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/logical_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/logistic.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/logistic.d ./tensorflow-lite/tensorflow/lite/micro/kernels/logistic.o ./tensorflow-lite/tensorflow/lite/micro/kernels/logistic.su ./tensorflow-lite/tensorflow/lite/micro/kernels/logistic_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/logistic_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/logistic_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/logistic_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval.d ./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval.o ./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval.su ./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/lstm_eval_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/maximum_minimum.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/maximum_minimum.d ./tensorflow-lite/tensorflow/lite/micro/kernels/maximum_minimum.o ./tensorflow-lite/tensorflow/lite/micro/kernels/maximum_minimum.su ./tensorflow-lite/tensorflow/lite/micro/kernels/micro_tensor_utils.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./tensorflow-lite/tensorflow/lite/micro/kernels/micro_tensor_utils.o ./tensorflow-lite/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./tensorflow-lite/tensorflow/lite/micro/kernels/mirror_pad.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/mirror_pad.d ./tensorflow-lite/tensorflow/lite/micro/kernels/mirror_pad.o ./tensorflow-lite/tensorflow/lite/micro/kernels/mirror_pad.su ./tensorflow-lite/tensorflow/lite/micro/kernels/mul_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/mul_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/mul_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/mul_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/neg.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/neg.d ./tensorflow-lite/tensorflow/lite/micro/kernels/neg.o ./tensorflow-lite/tensorflow/lite/micro/kernels/neg.su ./tensorflow-lite/tensorflow/lite/micro/kernels/pack.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/pack.d ./tensorflow-lite/tensorflow/lite/micro/kernels/pack.o ./tensorflow-lite/tensorflow/lite/micro/kernels/pack.su ./tensorflow-lite/tensorflow/lite/micro/kernels/pad.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/pad.d ./tensorflow-lite/tensorflow/lite/micro/kernels/pad.o ./tensorflow-lite/tensorflow/lite/micro/kernels/pad.su ./tensorflow-lite/tensorflow/lite/micro/kernels/pooling_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/pooling_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/pooling_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/pooling_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/prelu.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/prelu.d ./tensorflow-lite/tensorflow/lite/micro/kernels/prelu.o ./tensorflow-lite/tensorflow/lite/micro/kernels/prelu.su ./tensorflow-lite/tensorflow/lite/micro/kernels/prelu_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/prelu_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/prelu_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/prelu_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/quantize.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/quantize.d ./tensorflow-lite/tensorflow/lite/micro/kernels/quantize.o ./tensorflow-lite/tensorflow/lite/micro/kernels/quantize.su ./tensorflow-lite/tensorflow/lite/micro/kernels/quantize_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/quantize_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/quantize_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/quantize_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/read_variable.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/read_variable.d ./tensorflow-lite/tensorflow/lite/micro/kernels/read_variable.o ./tensorflow-lite/tensorflow/lite/micro/kernels/read_variable.su ./tensorflow-lite/tensorflow/lite/micro/kernels/reduce.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/reduce.d ./tensorflow-lite/tensorflow/lite/micro/kernels/reduce.o ./tensorflow-lite/tensorflow/lite/micro/kernels/reduce.su ./tensorflow-lite/tensorflow/lite/micro/kernels/reduce_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/reduce_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/reduce_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/reduce_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/reshape.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/reshape.d ./tensorflow-lite/tensorflow/lite/micro/kernels/reshape.o ./tensorflow-lite/tensorflow/lite/micro/kernels/reshape.su ./tensorflow-lite/tensorflow/lite/micro/kernels/reshape_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/reshape_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/reshape_common.o
	-$(RM) ./tensorflow-lite/tensorflow/lite/micro/kernels/reshape_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/resize_bilinear.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/resize_bilinear.d ./tensorflow-lite/tensorflow/lite/micro/kernels/resize_bilinear.o ./tensorflow-lite/tensorflow/lite/micro/kernels/resize_bilinear.su ./tensorflow-lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./tensorflow-lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./tensorflow-lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./tensorflow-lite/tensorflow/lite/micro/kernels/round.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/round.d ./tensorflow-lite/tensorflow/lite/micro/kernels/round.o ./tensorflow-lite/tensorflow/lite/micro/kernels/round.su ./tensorflow-lite/tensorflow/lite/micro/kernels/select.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/select.d ./tensorflow-lite/tensorflow/lite/micro/kernels/select.o ./tensorflow-lite/tensorflow/lite/micro/kernels/select.su ./tensorflow-lite/tensorflow/lite/micro/kernels/shape.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/shape.d ./tensorflow-lite/tensorflow/lite/micro/kernels/shape.o ./tensorflow-lite/tensorflow/lite/micro/kernels/shape.su ./tensorflow-lite/tensorflow/lite/micro/kernels/slice.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/slice.d ./tensorflow-lite/tensorflow/lite/micro/kernels/slice.o ./tensorflow-lite/tensorflow/lite/micro/kernels/slice.su ./tensorflow-lite/tensorflow/lite/micro/kernels/softmax_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/softmax_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/softmax_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/softmax_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_batch_nd.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_depth.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_depth.d ./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_depth.o ./tensorflow-lite/tensorflow/lite/micro/kernels/space_to_depth.su ./tensorflow-lite/tensorflow/lite/micro/kernels/split.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/split.d ./tensorflow-lite/tensorflow/lite/micro/kernels/split.o ./tensorflow-lite/tensorflow/lite/micro/kernels/split.su ./tensorflow-lite/tensorflow/lite/micro/kernels/split_v.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/split_v.d ./tensorflow-lite/tensorflow/lite/micro/kernels/split_v.o ./tensorflow-lite/tensorflow/lite/micro/kernels/split_v.su ./tensorflow-lite/tensorflow/lite/micro/kernels/squared_difference.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/squared_difference.d ./tensorflow-lite/tensorflow/lite/micro/kernels/squared_difference.o ./tensorflow-lite/tensorflow/lite/micro/kernels/squared_difference.su ./tensorflow-lite/tensorflow/lite/micro/kernels/squeeze.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/squeeze.d ./tensorflow-lite/tensorflow/lite/micro/kernels/squeeze.o ./tensorflow-lite/tensorflow/lite/micro/kernels/squeeze.su ./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice.d ./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice.o ./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice.su ./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/strided_slice_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/sub.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/sub.d ./tensorflow-lite/tensorflow/lite/micro/kernels/sub.o ./tensorflow-lite/tensorflow/lite/micro/kernels/sub.su ./tensorflow-lite/tensorflow/lite/micro/kernels/sub_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/sub_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/sub_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/sub_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/svdf_common.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/svdf_common.d ./tensorflow-lite/tensorflow/lite/micro/kernels/svdf_common.o ./tensorflow-lite/tensorflow/lite/micro/kernels/svdf_common.su ./tensorflow-lite/tensorflow/lite/micro/kernels/tanh.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/tanh.d ./tensorflow-lite/tensorflow/lite/micro/kernels/tanh.o ./tensorflow-lite/tensorflow/lite/micro/kernels/tanh.su ./tensorflow-lite/tensorflow/lite/micro/kernels/transpose.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/transpose.d ./tensorflow-lite/tensorflow/lite/micro/kernels/transpose.o ./tensorflow-lite/tensorflow/lite/micro/kernels/transpose.su ./tensorflow-lite/tensorflow/lite/micro/kernels/unpack.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/unpack.d ./tensorflow-lite/tensorflow/lite/micro/kernels/unpack.o ./tensorflow-lite/tensorflow/lite/micro/kernels/unpack.su ./tensorflow-lite/tensorflow/lite/micro/kernels/var_handle.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/var_handle.d ./tensorflow-lite/tensorflow/lite/micro/kernels/var_handle.o ./tensorflow-lite/tensorflow/lite/micro/kernels/var_handle.su ./tensorflow-lite/tensorflow/lite/micro/kernels/while.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/while.d ./tensorflow-lite/tensorflow/lite/micro/kernels/while.o ./tensorflow-lite/tensorflow/lite/micro/kernels/while.su ./tensorflow-lite/tensorflow/lite/micro/kernels/zeros_like.cyclo ./tensorflow-lite/tensorflow/lite/micro/kernels/zeros_like.d ./tensorflow-lite/tensorflow/lite/micro/kernels/zeros_like.o
	-$(RM) ./tensorflow-lite/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-tensorflow-2d-lite-2f-tensorflow-2f-lite-2f-micro-2f-kernels

